


import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.EmptyBorder;
import java.awt.Font;
import javax.swing.JMenuItem;
import java.awt.Dimension;
import java.awt.Cursor;
import java.awt.Toolkit;

public class jf_consulta extends JFrame {

	private static final long serialVersionUID = 1L;
	private JPanel contentPane;

	/**
	 * Launch the application.
	 */
	Fondo fondo = new Fondo();
    public jf_consulta() {
    	setTitle("Gestión de consulta");
    	setIconImage(Toolkit.getDefaultToolkit().getImage(jf_consulta.class.getResource("/iconos_menus/dentilaxIcono.png")));
    	setPreferredSize(new Dimension(1450, 750));
        this.setContentPane(fondo);      
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_menu = new Fondo();
        btn_buscar_cita = new javax.swing.JButton();
        btn_buscar_cita.setBorderPainted(false);
        btn_buscar_cita.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        btn_nueva_cita = new javax.swing.JButton();
        btn_nueva_cita.setBorderPainted(false);
        btn_historial = new javax.swing.JButton();
        btn_historial.setBorderPainted(false);
        btn_eliminar_cita = new javax.swing.JButton();
        btn_eliminar_cita.setBorderPainted(false);
        btn_eliminar_cita.setText("ELIMINAR CITA");
        menu_inicio = new javax.swing.JMenuBar();
        jmenu_paciente = new javax.swing.JMenu();
        jmenu_paciente.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_doctor = new javax.swing.JMenu();
        jmenu_doctor.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_material = new javax.swing.JMenu();
        jmenu_material.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_consulta = new javax.swing.JMenu();
        jmenu_consulta.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_facturacion = new javax.swing.JMenu();
        jmenu_facturacion.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_ajustes = new javax.swing.JMenu();
        jmenu_ajustes.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_ayuda = new javax.swing.JMenu();
        jmenu_ayuda.setFont(new Font("Arial", Font.PLAIN, 12));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_buscar_cita.setText("BUSCAR CITA");

        btn_nueva_cita.setText("NUEVA CITA");

        btn_historial.setText("HISTORIAL");

        javax.swing.GroupLayout jp_menuLayout = new javax.swing.GroupLayout(jp_menu);
        jp_menuLayout.setHorizontalGroup(
        	jp_menuLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jp_menuLayout.createSequentialGroup()
        			.addGap(68)
        			.addComponent(btn_buscar_cita, GroupLayout.PREFERRED_SIZE, 146, GroupLayout.PREFERRED_SIZE)
        			.addGap(187)
        			.addComponent(btn_historial, GroupLayout.PREFERRED_SIZE, 146, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
        			.addComponent(btn_eliminar_cita, GroupLayout.PREFERRED_SIZE, 146, GroupLayout.PREFERRED_SIZE)
        			.addGap(172)
        			.addComponent(btn_nueva_cita, GroupLayout.PREFERRED_SIZE, 146, GroupLayout.PREFERRED_SIZE)
        			.addGap(79))
        );
        jp_menuLayout.setVerticalGroup(
        	jp_menuLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jp_menuLayout.createSequentialGroup()
        			.addContainerGap(596, Short.MAX_VALUE)
        			.addGroup(jp_menuLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btn_buscar_cita, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btn_nueva_cita, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btn_eliminar_cita, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btn_historial, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
        			.addGap(44))
        );
        jp_menu.setLayout(jp_menuLayout);

        menu_inicio.setBackground(new java.awt.Color(32, 160, 216));
        menu_inicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        menu_inicio.setBorderPainted(false);
        
        btn_inicio = new JButton("INICIO");
        btn_inicio.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btn_inicio.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		jf_menu_ppal ventana = new jf_menu_ppal();
        		ventana.setVisible(true);
        	}
        });
        btn_inicio.setOpaque(false);
        btn_inicio.setFont(new Font("Arial", Font.PLAIN, 12));
        btn_inicio.setFocusPainted(false);
        btn_inicio.setContentAreaFilled(false);
        btn_inicio.setBorderPainted(false);
        menu_inicio.add(btn_inicio);

        jmenu_paciente.setText("PACIENTES");
        menu_inicio.add(jmenu_paciente);
        
        jmenuitem_menu_paciente = new JMenuItem("Menu paciente");
        jmenuitem_menu_paciente.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		jf_pacientes ventana = new jf_pacientes();
        		dispose();
        		ventana.setVisible(true);
        	}
        });
        jmenuitem_menu_paciente.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_paciente.add(jmenuitem_menu_paciente);
        
        jmenuitem_buscar_paciente = new JMenuItem("Buscar paciente");
        jmenuitem_buscar_paciente.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		jf_pacientes ventana = new jf_pacientes();
        		jd_buscar_paciente ventana_buscar = new jd_buscar_paciente();
        		ventana.setVisible(true);
        		ventana_buscar.setVisible(true);
        	}
        });
        jmenuitem_buscar_paciente.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_paciente.add(jmenuitem_buscar_paciente);
        
        jmenuitem_editar_paciente = new JMenuItem("Editar paciente");
        jmenuitem_editar_paciente.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		jf_pacientes ventana = new jf_pacientes();
        		jd_buscar_paciente_editar ventana_buscar = new jd_buscar_paciente_editar();
        		ventana.setVisible(true);
        		ventana_buscar.setVisible(true);
        	}
        });
        jmenuitem_editar_paciente.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_paciente.add(jmenuitem_editar_paciente);
        
        jmenuitem_baja_paciente = new JMenuItem("Dar de baja");
        jmenuitem_baja_paciente.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
				jf_pacientes ventana = new jf_pacientes();
				jd_buscar_paciente_baja ventana_buscar = new jd_buscar_paciente_baja();
				ventana.setVisible(true);
				ventana_buscar.setVisible(true);
        	}
        });
        jmenuitem_baja_paciente.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_paciente.add(jmenuitem_baja_paciente);
        
        jmenuitem_alta_paciente = new JMenuItem("Dar de alta");
        jmenuitem_alta_paciente.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
				jf_pacientes ventana = new jf_pacientes();
				jd_pacientes_alta ventana_alta = new jd_pacientes_alta();
				ventana.setVisible(true);
				ventana_alta.setVisible(true);
        	}
        });
        jmenuitem_alta_paciente.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_paciente.add(jmenuitem_alta_paciente);

        jmenu_doctor.setText("DOCTORES");
        menu_inicio.add(jmenu_doctor);
        
        jmenuitem_menu_doctores = new JMenuItem("Menu doctor");
        jmenuitem_menu_doctores.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		jf_doctores ventana = new jf_doctores();
        		ventana.setVisible(true);
        	}
        });
        jmenuitem_menu_doctores.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_doctor.add(jmenuitem_menu_doctores);
        
        jmenuitem_buscar_doctores = new JMenuItem("Buscar doctor");
        jmenuitem_buscar_doctores.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		jf_doctores ventana = new jf_doctores();
        		jd_buscar_dr ventana_buscar = new jd_buscar_dr();
        		ventana.setVisible(true);
        		ventana_buscar.setVisible(true);
        	}
        });
        jmenuitem_buscar_doctores.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_doctor.add(jmenuitem_buscar_doctores);
        
        jmenuitem_especialidad_doctores = new JMenuItem("Especialidad");
        jmenuitem_especialidad_doctores.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		jf_doctores ventana = new jf_doctores();
        		jd_especialidades ventana_especialidad = new jd_especialidades();
        		ventana.setVisible(true);
        		ventana_especialidad.setVisible(true);
        	}
        });
        jmenuitem_especialidad_doctores.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_doctor.add(jmenuitem_especialidad_doctores);
        
        jmenuitem_editar_doctor = new JMenuItem("Editar doctor");
        jmenuitem_editar_doctor.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		jf_doctores ventana = new jf_doctores();
        		jd_buscar_doctor_editar ventana_buscar = new jd_buscar_doctor_editar();
        		ventana.setVisible(true);
        		ventana_buscar.setVisible(true);
        	}
        });
        jmenuitem_editar_doctor.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_doctor.add(jmenuitem_editar_doctor);
        
        jmenuitem_baja_doctores = new JMenuItem("Dar de baja");
        jmenuitem_baja_doctores.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		jf_doctores ventana = new jf_doctores();
        		jd_buscar_doctor_baja ventana_alta = new jd_buscar_doctor_baja();
        		ventana.setVisible(true);
        		ventana_alta.setVisible(true);
        	}
        });
        jmenuitem_baja_doctores.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_doctor.add(jmenuitem_baja_doctores);
        
        jmenuitem_alta_doctores = new JMenuItem("Dar de alta");
        jmenuitem_alta_doctores.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		jf_doctores ventana = new jf_doctores();
        		jd_doctores_alta ventana_alta = new jd_doctores_alta();
        		ventana.setVisible(true);
        		ventana_alta.setVisible(true);
        	}
        });
        jmenuitem_alta_doctores.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_doctor.add(jmenuitem_alta_doctores);

        jmenu_material.setText("MATERIAL");
        menu_inicio.add(jmenu_material);
        
        jmenuitem_menu_material = new JMenuItem("Menu material");
        jmenuitem_menu_material.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		jf_material ventana = new jf_material();
        		ventana.setVisible(true);
        	}
        });
        jmenuitem_menu_material.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_material.add(jmenuitem_menu_material);
        
        jmenuitem_buscar_pedido = new JMenuItem("Buscar pedido");
        jmenuitem_buscar_pedido.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_material.add(jmenuitem_buscar_pedido);
        
        jmenuitem_proveedores = new JMenuItem("Proveedores");
        jmenuitem_proveedores.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_material.add(jmenuitem_proveedores);
        
        jmenuitem_cancelar = new JMenuItem("Cancelar pedido");
        jmenuitem_cancelar.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_material.add(jmenuitem_cancelar);
        
        jmenuitem_nuevo_pedido = new JMenuItem("Nuevo pedido");
        jmenuitem_nuevo_pedido.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_material.add(jmenuitem_nuevo_pedido);
        
        jmenuitem_inventario = new JMenuItem("Inventario");
        jmenuitem_inventario.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_material.add(jmenuitem_inventario);
        
        jmenuitem_solicitudes = new JMenuItem("Solicitudes");
        jmenuitem_solicitudes.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_material.add(jmenuitem_solicitudes);

        jmenu_consulta.setText("CONSULTAS");
        menu_inicio.add(jmenu_consulta);
        
        jmenuitem_menu_consulta = new JMenuItem("Menu consulta");
        jmenuitem_menu_consulta.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		jf_consulta ventana = new jf_consulta();
        		ventana.setVisible(true);
        	}
        });
        jmenuitem_menu_consulta.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_consulta.add(jmenuitem_menu_consulta);
        
        jmenuitem_buscar_cita = new JMenuItem("Buscar cita");
        jmenuitem_buscar_cita.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_consulta.add(jmenuitem_buscar_cita);
        
        jmenuitem_historial = new JMenuItem("Historial");
        jmenuitem_historial.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_consulta.add(jmenuitem_historial);
        
        jmenuitem_eliminar_cita = new JMenuItem("Eliminar cita");
        jmenuitem_eliminar_cita.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_consulta.add(jmenuitem_eliminar_cita);
        
        jmenuitem_nueva_cita = new JMenuItem("Nueva cita");
        jmenuitem_nueva_cita.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_consulta.add(jmenuitem_nueva_cita);

        jmenu_facturacion.setText("FACTURACIÓN");
        menu_inicio.add(jmenu_facturacion);
        
        jmenuitem_menu_facturacion = new JMenuItem("Menu facturacion");
        jmenuitem_menu_facturacion.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		jf_facturacion ventana = new jf_facturacion();
        		ventana.setVisible(true);
        	}
        });
        jmenuitem_menu_facturacion.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_facturacion.add(jmenuitem_menu_facturacion);
        
        jmenuitem_buscar_factura = new JMenuItem("Buscar factura");
        jmenuitem_buscar_factura.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_facturacion.add(jmenuitem_buscar_factura);
        
        jmenuitem_historial_pago = new JMenuItem("Historial de pago");
        jmenuitem_historial_pago.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_facturacion.add(jmenuitem_historial_pago);
        
        jmenuitem_balance_gastos = new JMenuItem("Balance de gastos");
        jmenuitem_balance_gastos.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_facturacion.add(jmenuitem_balance_gastos);
        
        jmenuitem_nueva_factura = new JMenuItem("Nueva factura");
        jmenuitem_nueva_factura.setFont(new Font("Arial", Font.PLAIN, 12));
        jmenu_facturacion.add(jmenuitem_nueva_factura);

        jmenu_ajustes.setText("AJUSTES");
        menu_inicio.add(jmenu_ajustes);

        jmenu_ayuda.setText("AYUDA");
        menu_inicio.add(jmenu_ayuda);

        setJMenuBar(menu_inicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jf_consulta().setVisible(true);
            }
        });
    }
    private javax.swing.JButton btn_historial;
    private javax.swing.JButton btn_nueva_cita;
    private javax.swing.JButton btn_buscar_cita;
    private javax.swing.JMenu jmenu_paciente;
    private javax.swing.JMenu jmenu_doctor;
    private javax.swing.JMenu jmenu_material;
    private javax.swing.JMenu jmenu_consulta;
    private javax.swing.JMenu jmenu_facturacion;
    private javax.swing.JMenu jmenu_ajustes;
    private javax.swing.JMenu jmenu_ayuda;
    private javax.swing.JPanel jp_menu;
    private javax.swing.JMenuBar menu_inicio;
    private JButton btn_eliminar_cita;
    private JButton btn_inicio;
    private JMenuItem jmenuitem_menu_paciente;
    private JMenuItem jmenuitem_alta_paciente;
    private JMenuItem jmenuitem_buscar_paciente;
    private JMenuItem jmenuitem_editar_paciente;
    private JMenuItem jmenuitem_baja_paciente;
    private JMenuItem jmenuitem_menu_doctores;
    private JMenuItem jmenuitem_alta_doctores;
    private JMenuItem jmenuitem_buscar_doctores;
    private JMenuItem jmenuitem_especialidad_doctores;
    private JMenuItem jmenuitem_baja_doctores;
    private JMenuItem jmenuitem_editar_doctor;
    private JMenuItem jmenuitem_menu_material;
    private JMenuItem jmenuitem_buscar_pedido;
    private JMenuItem jmenuitem_proveedores;
    private JMenuItem jmenuitem_solicitudes;
    private JMenuItem jmenuitem_inventario;
    private JMenuItem jmenuitem_cancelar;
    private JMenuItem jmenuitem_nuevo_pedido;
    private JMenuItem jmenuitem_menu_consulta;
    private JMenuItem jmenuitem_nueva_cita;
    private JMenuItem jmenuitem_buscar_cita;
    private JMenuItem jmenuitem_historial;
    private JMenuItem jmenuitem_eliminar_cita;
    private JMenuItem jmenuitem_menu_facturacion;
    private JMenuItem jmenuitem_nueva_factura;
    private JMenuItem jmenuitem_balance_gastos;
    private JMenuItem jmenuitem_buscar_factura;
    private JMenuItem jmenuitem_historial_pago;
    // End of variables declaration//GEN-END:variables

}
