
import java.awt.Color;
import java.awt.event.ActionListener;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.border.EmptyBorder;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import java.awt.Cursor;
import java.awt.Image;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Dimension;
import javax.swing.SwingConstants;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *hola que tal
 * @author alexg
 */
public class jf_login extends javax.swing.JFrame {

	
	
    public javax.swing.JTextField getJtf_user() {
		return jtf_user;
	}

	public void setJtf_user(javax.swing.JTextField jtf_user) {
		this.jtf_user = jtf_user;
	}

	public javax.swing.JTextField getJtf_user1() {
		return jtf_user1;
	}

	public void setJtf_user1(javax.swing.JTextField jtf_user1) {
		this.jtf_user1 = jtf_user1;
	}

	/**
     * Creates new form jf_login
     */
    Fondo fondo = new Fondo();
    public jf_login() {
    	setPreferredSize(new Dimension(1450, 750));
        this.setContentPane(fondo);
        initComponents();
        panelFondo.setLayout(null);
        Panel p = new Panel("/Dentilax/imagenes/iconos_menus/panel_login.png");
        p.setBounds(0, 0, 0, 0);
        panelFondo.add(p);
        panelFondo.add(p);
        panelFondo.add(interior);
        interior.setLayout(null);
        interior.add(cb_recordar);
        interior.add(btn_recuperar_pass);
        interior.add(jPanel1);
        jPanel1.setLayout(null);
        jPanel1.add(jPanel3);
        interior.add(jPanel2);
        jPanel2.setLayout(null);
        jPanel2.add(jPanel4);
        interior.add(jtf_user1);
        interior.add(jtf_user);
        panelFondo.add(btn_entrar);
        
        lblNewLabel = new JLabel("");
        lblNewLabel.setBounds(486, 93, 500, 450);
        panelFondo.add(lblNewLabel);
        lblNewLabel.setIcon(new ImageIcon(jf_login.class.getResource("/iconos_menus/panel_login.png")));
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	//comentario de prueba
    	 ConectorDB_mysql sentencias = new ConectorDB_mysql();
        panelFondo = new Fondo();
        panelFondo.setPreferredSize(new Dimension(1450, 750));
        panelFondo.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        panelFondo.setOpaque(false);
        panelFondo.setBorder(null);
        interior = new javax.swing.JPanel();
        interior.setBounds(497, 141, 483, 350);
        interior.setOpaque(false);
        jtf_user = new javax.swing.JTextField();
        jtf_user.setForeground(new Color(0, 128, 192));
        jtf_user.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusGained(FocusEvent e) {
        		if (jtf_user.getText().equals("Introduce usuario")) {
                    jtf_user.setText("");
                    jtf_user.setForeground(Color.BLACK);
                }
        	}
        	@Override
        	public void focusLost(FocusEvent e) {
        		 if (jtf_user.getText().isEmpty()) {
                     jtf_user.setForeground(new Color(0, 128, 192));
                     jtf_user.setText("Introduce usuario");
                 }
        	}
        });
        jtf_user.setHorizontalAlignment(SwingConstants.CENTER);
        jtf_user.setToolTipText("Introduce el DNI del usuario");
        
        jtf_user.setBorder(null);
        jtf_user.setCaretColor(new Color(255, 255, 255));
        jtf_user.setBounds(132, 83, 294, 65);
        jtf_user1 = new javax.swing.JTextField();
        jtf_user1.setForeground(new Color(0, 128, 192));
        jtf_user1.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusGained(FocusEvent e) {
        		if (jtf_user1.getText().equals("Introduce contraseña")) {
                    jtf_user1.setText("");
                    jtf_user1.setForeground(Color.BLACK);
                }
        	}
        	@Override
        	public void focusLost(FocusEvent e) {
        		if (jtf_user1.getText().isEmpty()) {
                    jtf_user1.setForeground(new Color(0, 128, 192));
                    jtf_user1.setText("Introduce contraseña");
                }
        	}
        });
        jtf_user1.setHorizontalAlignment(SwingConstants.CENTER);
        jtf_user1.setToolTipText("Introduce contraseña");
        jtf_user1.setBorder(null);
        jtf_user1.setBounds(132, 199, 294, 65);
        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBounds(63, 199, 63, 65);
        jPanel3 = new FondoPass();
        jPanel3.setBounds(10, 11, 43, 43);
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setBounds(63, 83, 63, 65);
        jPanel4 = new FondoUser();
        jPanel4.setBounds(10, 11, 43, 43);
        cb_recordar = new javax.swing.JCheckBox();
        cb_recordar.setBounds(63, 289, 103, 23);
        btn_recuperar_pass = new javax.swing.JButton();
        btn_recuperar_pass.setBorderPainted(false);
        btn_recuperar_pass.setBounds(269, 289, 157, 23);
        btn_entrar = new javax.swing.JButton();
        btn_entrar.setBorderPainted(false);
        btn_entrar.setBounds(551, 572, 375, 63);
        btn_entrar.setContentAreaFilled(false);
        btn_entrar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btn_entrar.setBorder(null);
        btn_entrar.setOpaque(false);
        btn_entrar.setToolTipText("Pulsa para logearte");
        btn_entrar.setIcon(new ImageIcon(jf_login.class.getResource("/iconos_menus/btn_entrar_icon.png")));
        
        
        
        btn_entrar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
               
               try {
            	String user = jtf_user.getText().toString();
            	String pass = jtf_user1.getText().toString();
				String comprobar = sentencias.consulta_login(user, pass);
				if (comprobar.equals("Admin")) {
				
					System.out.println("Estoy accediendo como administrador");
				jf_menu_ppal menu_admin = new jf_menu_ppal();
				menu_admin.setVisible(true);
				dispose();
}
				else {

					System.out.println("Estoy accediendo como doctor");

}
				
			} catch (SQLException e1) {
				// TODO Auto-generated catch block
				JOptionPane error = new JOptionPane();
				error.showMessageDialog(error, "Error en el login");
				e1.printStackTrace();
				
			}
               catch(NullPointerException n) {
            	   JOptionPane error = new JOptionPane();
            	   error.showMessageDialog(error, "No hay datos, comprueba la conexión a la base de datos "
            	   		+ "o en su defecto, que no haya campos vacíos y vuelve a intentarlo");
               }
            }
                
                
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        interior.setBackground(new java.awt.Color(255, 255, 255));

        jtf_user.setBackground(new java.awt.Color(128, 208, 244));
        jtf_user.setText("Introduce usuario");
        
        
        
        jtf_user1.setBackground(new java.awt.Color(128, 208, 244));
        jtf_user1.setText("Introduce contraseña");
        jtf_user1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_user1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(32, 160, 216));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(32, 160, 216));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        cb_recordar.setText("Recuérdame");

        btn_recuperar_pass.setText("Recuperar contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_user1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_user1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_user1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jf_login().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_entrar;
    private javax.swing.JButton btn_recuperar_pass;
    private javax.swing.JCheckBox cb_recordar;
    private javax.swing.JPanel interior;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jtf_user;
    private javax.swing.JTextField jtf_user1;
    private javax.swing.JPanel panelFondo;
    private JLabel lblNewLabel;
}
