import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Dimension;
import java.awt.Cursor;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alexg
 */
public class jf_menu_ppal extends javax.swing.JFrame {

    /**
     * Creates new form jf_menu_ppal
     */
    Fondo fondo = new Fondo();
    public jf_menu_ppal() {
    	setSize(new Dimension(1450, 750));
    	setResizable(false);
        this.setContentPane(fondo);      
        initComponents();
        this.setLocationRelativeTo(jp_menu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_menu = new Fondo();
        jp_menu.setPreferredSize(new Dimension(1450, 750));
        jp_menu.setSize(new Dimension(1450, 750));
        btn_pacientes = new javax.swing.JButton();
        btn_pacientes.setBorderPainted(false);
        btn_pacientes.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btn_pacientes.setOpaque(false);
        btn_pacientes.setContentAreaFilled(false);
        btn_pacientes.setIcon(new ImageIcon(jf_menu_ppal.class.getResource("/iconos_menus/btn_pacientes_admin.png")));
        btn_pacientes.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		jf_pacientes jf_pacientes = new jf_pacientes();
        		jf_pacientes.setVisible(true);
        	}
        });
        btn_material = new javax.swing.JButton();
        btn_material.setBorderPainted(false);
        btn_material.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btn_material.setOpaque(false);
        btn_material.setIcon(new ImageIcon(jf_menu_ppal.class.getResource("/iconos_menus/btn_material_admin.png")));
        btn_material.setContentAreaFilled(false);
        btn_material.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		dispose();
        		jf_material jf_material = new jf_material();
        		jf_material.setVisible(true);
        		
        	}
        });
        btn_facturacion = new javax.swing.JButton();
        btn_facturacion.setBorderPainted(false);
        btn_facturacion.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btn_facturacion.setIcon(new ImageIcon(jf_menu_ppal.class.getResource("/iconos_menus/btn_facturacion_admin.png")));
        btn_facturacion.setContentAreaFilled(false);
        btn_facturacion.setOpaque(false);
        btn_facturacion.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		dispose();
        		jf_facturacion jf_facturacion = new jf_facturacion();
        		jf_facturacion.setVisible(true);
        		
        	}
        });
        btn_ajustes = new javax.swing.JButton();
        btn_ajustes.setBorderPainted(false);
        btn_ajustes.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btn_ajustes.setIcon(new ImageIcon(jf_menu_ppal.class.getResource("/iconos_menus/btn_ajustes_admin.png")));
        btn_ajustes.setContentAreaFilled(false);
        btn_ajustes.setOpaque(false);
        btn_ajustes.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        btn_consultas = new javax.swing.JButton();
        btn_consultas.setBorderPainted(false);
        btn_consultas.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btn_consultas.setIcon(new ImageIcon(jf_menu_ppal.class.getResource("/iconos_menus/btn_consultas_admin.png")));
        btn_consultas.setContentAreaFilled(false);
        btn_consultas.setOpaque(false);
        btn_consultas.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		dispose();
        		jf_consulta jf_consulta = new jf_consulta();
        		jf_consulta.setVisible(true);
        		
        	}
        });
        btn_doctores = new javax.swing.JButton();
        btn_doctores.setBorderPainted(false);
        btn_doctores.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btn_doctores.setIcon(new ImageIcon(jf_menu_ppal.class.getResource("/iconos_menus/btn_doctores_admin.png")));
        btn_doctores.setContentAreaFilled(false);
        btn_doctores.setOpaque(false);
        btn_doctores.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		dispose();
        		jf_doctores jf_doctores = new jf_doctores();
        		jf_doctores.setVisible(true);
        		
        	}
        });
        menu_inicio = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jp_menuLayout = new javax.swing.GroupLayout(jp_menu);
        jp_menuLayout.setHorizontalGroup(
        	jp_menuLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jp_menuLayout.createSequentialGroup()
        			.addContainerGap(440, Short.MAX_VALUE)
        			.addGroup(jp_menuLayout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(btn_facturacion, 0, 0, Short.MAX_VALUE)
        				.addComponent(btn_pacientes, GroupLayout.PREFERRED_SIZE, 277, Short.MAX_VALUE)
        				.addComponent(btn_material, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 281, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
        			.addGroup(jp_menuLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jp_menuLayout.createParallelGroup(Alignment.LEADING, false)
        					.addComponent(btn_consultas, 0, 0, Short.MAX_VALUE)
        					.addComponent(btn_doctores, GroupLayout.PREFERRED_SIZE, 273, Short.MAX_VALUE))
        				.addComponent(btn_ajustes, GroupLayout.PREFERRED_SIZE, 273, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(441, Short.MAX_VALUE))
        );
        jp_menuLayout.setVerticalGroup(
        	jp_menuLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jp_menuLayout.createSequentialGroup()
        			.addGap(218)
        			.addGroup(jp_menuLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btn_pacientes, GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
        				.addComponent(btn_doctores, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE))
        			.addGap(4)
        			.addGroup(jp_menuLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(btn_consultas, GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        				.addComponent(btn_material, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jp_menuLayout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(btn_facturacion, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(btn_ajustes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addGap(217))
        );
        jp_menu.setLayout(jp_menuLayout);

        menu_inicio.setBackground(new java.awt.Color(32, 160, 216));
        menu_inicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        menu_inicio.setBorderPainted(false);

        jMenu1.setBackground(new java.awt.Color(32, 160, 216));
        jMenu1.setText("INICIO");
        menu_inicio.add(jMenu1);

        jMenu2.setText("PACIENTES");
        menu_inicio.add(jMenu2);

        jMenu3.setText("DOCTORES");
        menu_inicio.add(jMenu3);

        jMenu4.setText("MATERIAL");
        menu_inicio.add(jMenu4);

        jMenu5.setText("CONSULTAS");
        menu_inicio.add(jMenu5);

        jMenu6.setText("FACTURACIÓN");
        menu_inicio.add(jMenu6);

        jMenu7.setText("AJUSTES");
        menu_inicio.add(jMenu7);

        jMenu8.setText("AYUDA");
        menu_inicio.add(jMenu8);

        setJMenuBar(menu_inicio);
        
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jf_menu_ppal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajustes;
    private javax.swing.JButton btn_consultas;
    private javax.swing.JButton btn_doctores;
    private javax.swing.JButton btn_facturacion;
    private javax.swing.JButton btn_material;
    private javax.swing.JButton btn_pacientes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JPanel jp_menu;
    private javax.swing.JMenuBar menu_inicio;
    // End of variables declaration//GEN-END:variables
}
