import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JMenu;
import javax.swing.JSeparator;
import java.awt.Color;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alexg
 */
public class jf_menu_doctor extends javax.swing.JFrame {

    /**
     * Creates new form jf_menu_ppal
     */
    Fondo fondo = new Fondo();
    public jf_menu_doctor() {
        this.setContentPane(fondo);      
        initComponents();
        this.setLocationRelativeTo(jp_menu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_menu = new Fondo();
        btn_buscar_paciente = new javax.swing.JButton();
        btn_solicitar = new javax.swing.JButton();
        btn_ajustes = new javax.swing.JButton();
        btn_nuevo_tratamiento = new javax.swing.JButton();
        menu_inicio = new javax.swing.JMenuBar();
        mn_buscar = new javax.swing.JMenu();
        mn_tratamiento = new javax.swing.JMenu();
        mn_solictar = new javax.swing.JMenu();
        mn_ajustes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_buscar_paciente.setText("BUSCAR PACIENTE");

        btn_solicitar.setText("SOLICITAR MATERIAL");

        btn_ajustes.setText("AJUSTES");

        btn_nuevo_tratamiento.setText("NUEVO TRATAMIENTO");

        javax.swing.GroupLayout jp_menuLayout = new javax.swing.GroupLayout(jp_menu);
        jp_menuLayout.setHorizontalGroup(
        	jp_menuLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jp_menuLayout.createSequentialGroup()
        			.addGap(524)
        			.addGroup(jp_menuLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jp_menuLayout.createSequentialGroup()
        					.addComponent(btn_buscar_paciente, GroupLayout.PREFERRED_SIZE, 191, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(btn_nuevo_tratamiento, GroupLayout.PREFERRED_SIZE, 191, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jp_menuLayout.createSequentialGroup()
        					.addComponent(btn_solicitar, GroupLayout.PREFERRED_SIZE, 191, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(btn_ajustes, GroupLayout.PREFERRED_SIZE, 191, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(526, Short.MAX_VALUE))
        );
        jp_menuLayout.setVerticalGroup(
        	jp_menuLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jp_menuLayout.createSequentialGroup()
        			.addGap(218)
        			.addGroup(jp_menuLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btn_buscar_paciente, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btn_nuevo_tratamiento, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE))
        			.addGap(15)
        			.addGroup(jp_menuLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btn_solicitar, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btn_ajustes, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(347, Short.MAX_VALUE))
        );
        jp_menu.setLayout(jp_menuLayout);

        menu_inicio.setBackground(new java.awt.Color(32, 160, 216));
        menu_inicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        menu_inicio.setBorderPainted(false);

        mn_buscar.setBackground(new java.awt.Color(32, 160, 216));
        mn_buscar.setText("BUSCAR PACIENTE");
        menu_inicio.add(mn_buscar);

        mn_tratamiento.setText("NUEVO TRATAMIENTO");
        menu_inicio.add(mn_tratamiento);

        mn_solictar.setText("SOLICITAR MATERIAL");
        menu_inicio.add(mn_solictar);

        mn_ajustes.setText("AJUSTES");
        menu_inicio.add(mn_ajustes);

        setJMenuBar(menu_inicio);
        
        separator = new JSeparator();
        separator.setBackground(new Color(255, 255, 255));
        separator.setForeground(new Color(255, 255, 255));
        menu_inicio.add(separator);
        
        mn_ayuda = new JMenu("AYUDA");
        menu_inicio.add(mn_ayuda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jf_menu_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jf_menu_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jf_menu_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jf_menu_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jf_menu_doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajustes;
    private javax.swing.JButton btn_nuevo_tratamiento;
    private javax.swing.JButton btn_solicitar;
    private javax.swing.JButton btn_buscar_paciente;
    private javax.swing.JMenu mn_buscar;
    private javax.swing.JMenu mn_tratamiento;
    private javax.swing.JMenu mn_solictar;
    private javax.swing.JMenu mn_ajustes;
    private javax.swing.JPanel jp_menu;
    private javax.swing.JMenuBar menu_inicio;
    private JMenu mn_ayuda;
    private JSeparator separator;
}
